{
 "title": "Node (public)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": {
     "query": "query_result(label_join( max by (hostname,nodeid) (node_clients.total[1y]) , \"result\", \" - \", \"nodeid\", \"hostname\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Knoteninformationen",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (nodeid,hostname,firmware_base,firmware_release,model,owner,autoupdater) (node_time.up{nodeid=\"$node_id\"}[1y])"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by (nodeid) (irate(node_traffic.forward.bytes{nodeid=\"$node_id\"})[2m])",
     "legendFormat": "Traffic (forward)"
    },
    {
     "expr": "max by (nodeid) (irate(node_traffic.rx.bytes{nodeid=\"$node_id\"})[2m])",
     "legendFormat": "Traffic (rx)"
    },
    {
     "expr": "max by (nodeid) (irate(node_traffic.tx.bytes{nodeid=\"$node_id\"})[2m])",
     "legendFormat": "Traffic (tx)"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (nodeid)(max_over_time(node_clients.total{nodeid=\"$node_id\"}[3m]))",
     "legendFormat": "clients"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.forward.bytes{nodeid=\"$node_id\"}[1y])),\"interval\",\"1y\",\"\",\"\"),\"traffic\",\"forward\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.rx.bytes{nodeid=\"$node_id\"}[1y])),\"interval\",\"1y\",\"\",\"\"),\"traffic\",\"rx\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.tx.bytes{nodeid=\"$node_id\"}[1y])),\"interval\",\"1y\",\"\",\"\"),\"traffic\",\"tx\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.forward.bytes{nodeid=\"$node_id\"}[30d])),\"interval\",\"30d\",\"\",\"\"),\"traffic\",\"forward\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.rx.bytes{nodeid=\"$node_id\"}[30d])),\"interval\",\"30d\",\"\",\"\"),\"traffic\",\"rx\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.tx.bytes{nodeid=\"$node_id\"}[30d])),\"interval\",\"30d\",\"\",\"\"),\"traffic\",\"tx\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.forward.bytes{nodeid=\"$node_id\"}[24h])),\"interval\",\"24h\",\"\",\"\"),\"traffic\",\"forward\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.rx.bytes{nodeid=\"$node_id\"}[24h])),\"interval\",\"24h\",\"\",\"\"),\"traffic\",\"rx\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.tx.bytes{nodeid=\"$node_id\"}[24h])),\"interval\",\"24h\",\"\",\"\"),\"traffic\",\"tx\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.forward.bytes{nodeid=\"$node_id\"}[1h])),\"interval\",\"1h\",\"\",\"\"),\"traffic\",\"forward\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.rx.bytes{nodeid=\"$node_id\"}[1h])),\"interval\",\"1h\",\"\",\"\"),\"traffic\",\"rx\",\"\",\"\")"
    },
    {
     "expr": "label_replace(label_replace(max by (nodeid) (increase(node_traffic.tx.bytes{nodeid=\"$node_id\"}[1h])),\"interval\",\"1h\",\"\",\"\"),\"traffic\",\"tx\",\"\",\"\")"
    }
   ]
  },
  {
   "title": "Links zu anderen Knoten",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (target.id,target.hostname) (link_tq{source.id=\"$node_id\"})",
     "legendFormat": "to {{target.id}} {{target.hostname}}"
    },
    {
     "expr": "avg by (source.id,source.hostname) (link_tq{target.id=\"$node_id\"})",
     "legendFormat": "from {{source.id}} {{source.hostname}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by (nodeid) (node_load{nodeid=\"$node_id\"})",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "max by (nodeid) (node_memory.total{nodeid=\"$node_id\"})",
     "legendFormat": "total"
    },
    {
     "expr": "max by (nodeid) (node_memory.total{nodeid=\"$node_id\"}-node_memory.available{nodeid=\"$node_id\"})",
     "legendFormat": "used"
    }
   ]
  }
 ]
}