"extraObjects":
- "apiVersion": |-
    cert-manager.io/v1
  "kind": |-
    ClusterIssuer
  "metadata":
    "name": |-
      letsencrypt
  "spec":
    "acme":
      "email": ""
      "privateKeySecretRef":
        "name": |-
          letsencrypt
      "server": |-
        https://acme-v02.api.letsencrypt.org/directory
      "solvers":
      - "http01":
          "ingress": {}
"ingressShim":
  "defaultIssuerKind": |-
    ClusterIssuer
  "defaultIssuerName": |-
    letsencrypt
"installCRDs": !!bool |-
  true
"prometheus":
  "enabled": !!bool |-
    false
  "servicemonitor":
    "enabled": !!bool |-
      false
