---

- name: Create k3s directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  with_items:
    - /data/k3s
    - /var/lib/kubelet

- name: Configure k3s
  copy:
    dest: /data/k3s/docker-compose.yaml
    content: |
      version: '3.3'
      services:

        server:
          image: "rancher/k3s:{{K3S_VERSION}}"
          network_mode: host
          pid: host
          command:
          - server
          - --snapshotter=native
          - --https-listen-port=6443
          - --disable=traefik
          - --tls-san={{ inventory_hostname }}
          - --default-local-storage-path=/data/k3s/volumes
          - --docker
          tmpfs:
          - /run
          ulimits:
            nproc: 65535
            nofile:
              soft: 65535
              hard: 65535
          privileged: true
          restart: unless-stopped
          environment:
          - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
          - K3S_KUBECONFIG_MODE=600
          volumes:
          - ./k3s-server:/var/lib/rancher/k3s
          - /data:/data
          - /var/run/docker.sock:/var/run/docker.sock
          - type: bind
            source: /var/lib/docker
            target: /var/lib/docker
            bind:
              propagation: rshared
          - type: bind
            source: /var/lib/kubelet
            target: /var/lib/kubelet
            bind:
              propagation: rshared   
          - /sys:/sys
          # This is just so that we get the kubeconfig file out
          - .:/output

- name: Restart k3s
  shell: |
    cd /data/k3s
    docker-compose up -d
