apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ffmapserver.fullname" . }}-meshviewer
  labels:
    helm.sh/chart: {{ include "ffmapserver.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "ffmapserver.name" . }}-fastd-yanic
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ffmapserver.fullname" . }}-fastd-yanic
  labels:
    helm.sh/chart: {{ include "ffmapserver.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "ffmapserver.name" . }}-fastd-yanic
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ffmapserver.name" . }}-fastd-yanic
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ffmapserver.name" . }}-fastd-yanic
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: fastd
          image: "{{ .Values.fastd.image.repository }}:{{ .Values.fastd.image.tag }}"
          imagePullPolicy: {{ .Values.fastd.image.pullPolicy }}
          env:
            - name: FASTD_MTU
              value: {{ required "fastd.mtu" .Values.fastd.mtu | quote }}
            {{- range $i, $e := (required "fastd.peers" .Values.fastd.peers )}}
            - name: FASTD_PEER{{ add $i 1 }}_NAME
              value: {{ required "fastd.peers.name" $e.name | quote }}
            - name: FASTD_PEER{{ add $i 1 }}_REMOTE
              value: {{ required "fastd.peers.remote" $e.remote | quote }}
            - name: FASTD_PEER{{ add $i 1 }}_KEY
              value: {{ required "fastd.peers.key" $e.key | quote }}
            {{- end }}
            - name: FASTD_LOG_LEVEL
              value: {{ default "info" .Values.fastd.logLevel }}
            {{- if .Values.fastd.ipv6Prefix }}
            - name: IPV6_PREFIX
              value: {{ .Values.fastd.ipv6Prefix }}
            {{- end }}
          securityContext:
            privileged: true
          startupProbe:
            exec:
              command:
              - /healthcheck.sh
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 60
          livenessProbe:
            exec:
              command:
              - /healthcheck.sh
            timeoutSeconds: 3
            periodSeconds: 30
            failureThreshold: 10
        - name: yanic
          image: "{{ .Values.yanic.image.repository }}:{{ .Values.yanic.image.tag }}"
          imagePullPolicy: {{ .Values.yanic.image.pullPolicy }}
          ports:
            - name: respondd
              containerPort: 10011
              protocol: UDP
          env:
            - name: INFLUXDB_URL
              value: "http://{{ include "ffmapserver.fullname" . }}-vmserver:8428"
          volumeMounts:
            - name: meshviewer-data
              mountPath: /data
      volumes:
      - name: meshviewer-data
        persistentVolumeClaim:
          claimName: {{ include "ffmapserver.fullname" . }}-meshviewer

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---


apiVersion: v1
kind: Service
metadata:
  name: {{ include "ffmapserver.fullname" . }}-fastd-yanic
  labels:
    helm.sh/chart: {{ include "ffmapserver.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "ffmapserver.name" . }}-fastd-yanic
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - port: 10011
    name: respondd
    protocol: UDP
  selector:
      app.kubernetes.io/name: {{ include "ffmapserver.name" . }}-fastd-yanic
      app.kubernetes.io/instance: {{ .Release.Name }}
