context: ffle

charts:

  - name: victoria-metrics-k8s-stack
    namespace: monitoring
    chart:
      repo: https://victoriametrics.github.io/helm-charts/
      name: victoria-metrics-k8s-stack
      version: 0.6.1
    values:
      grafana:
        enabled: false

  - name: certmanager
    namespace: infrastructure
    chart:
      path: ../../helm-charts/certmanager

  - name: nginx-ingress
    namespace: infrastructure
    chart:
      repo: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx
      version: 4.0.13 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
    values:
      controller:
        watchIngressWithoutClass: true
        hostPort:
          enabled: true
        ingressClassResource:
          default: true
        service:
          enabled: false
        updateStrategy:
          type: Recreate
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
      defaultBackend:
        enabled: true

  - name: backup
    namespace: infrastructure
    chart:
      path: ../../helm-charts/backup
    values:
      resticRepositoryUrl: s3:https://s3.eu-central-003.backblazeb2.com/backup-ffle-mapserver
      resticPassword: <SECRET>+GO41xBp02XLKv7q0N2WZfiAdwlOOmI5zLfAALfUl70ir1c2wlDBkE54e5Qu0jY4ozFdTkXkTQQ8NHX1YzUD51ad6L5U
      s3Key: 003aade47394c0c0000000001
      s3Secret: <SECRET>+GO41xBb0QOvHObToODPTruNYAcLE0QhouzCSbXmkpkJ2kca
      nodeSelectorRequired: false
      volumes:
        - name: k3s
          hostPath: /data/k3s
      
