context: ffle

charts:

  - name: victoria-metrics-k8s-stack
    namespace: monitoring
    chart:
      repo: https://victoriametrics.github.io/helm-charts/
      name: victoria-metrics-k8s-stack
      version: 0.6.1
    values:
      grafana:
        enabled: false

  - name: certmanager
    namespace: infrastructure
    chart:
      path: ../../helm-charts/certmanager

  - name: nginx-ingress
    namespace: infrastructure
    chart:
      repo: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx
      version: 4.0.13 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
    values:
      controller:
        watchIngressWithoutClass: true
        hostPort:
          enabled: true
        ingressClassResource:
          default: true
        service:
          enabled: false
        updateStrategy:
          type: Recreate
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
      defaultBackend:
        enabled: true
