context: ffle

charts:

  - name: mapserver
    namespace: mapserver
    chart:
      path: ../../helm-charts/ffmapserver
    values:
      domain: karte.freifunk-leipzig.de
      fastd:
        mtu: 1426
        peers:
          - name: vpngluon1
            remote: '"gluon20162a61.leipzig.freifunk.net" port 10061'
            key: 7e383ce9ba4fea8a82c1860864c2f940ef9f8a92b04f62fb7ac5f57442872f0e
          - name: vpngluon2
            remote: '"gluon20171b61.leipzig.freifunk.net" port 10061'
            key: 6a5e3d0d88feb0350078b5ce7c7a15baf918e0c2455d6854ec933c96c7a01a43
          - name: vpngluon3
            remote: '"gluon20162c61.leipzig.freifunk.net" port 10061'
            key: 4414df684d9d6e28f845753e4c9c1ebe2cc041f567ca3f09cafb51b73d19ea6b
        logLevel: info
        ipv6Prefix: fdef:ffc0:7030::/64
