---

cert-manager:
  installCRDs: true

  ingressShim:
    defaultIssuerName: "letsencrypt"
    defaultIssuerKind: "ClusterIssuer"

  prometheus:
    enabled: false
    servicemonitor:
      enabled: false
